services:
  gestacao-segura:
    image: 'gestacao-segura:latest'
    build:
      context: .
    container_name: gestacao-segura-api
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}?currentSchema=fiap
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - gestacao-segura-api-network

networks:
  gestacao-segura-api-network:
    driver: bridge
